import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header/Header";
import { Footer } from "@/components";
import { CTASection } from "@/components";
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${poppins.variable} h-full antialiased`}
    >
      <body className={poppins.className}>
        <Header/>
        {children}
        <CTASection
          title="Connect With Our CA Team"
          subtitle="Professional support for taxation, compliance, registration, and financial services."
        />
        <Footer />
      </body>
    </html>
  );
}